.github/workflows/deploy.yml

Since we change the default branch name, we should update the `deploy.yml` correspondingly.

[workflow] Change the deploy branch to `master`.

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/content-bug.yml
.github/ISSUE_TEMPLATE/content-request.yml
.github/ISSUE_TEMPLATE/feature-request.yml
.github/ISSUE_TEMPLATE/request-for-comment.yml
.github/PULL_REQUEST_TEMPLATE.md

To promote a more standardized community development, I believe its' essential to introduce templates to standardize the format of issues and pull requests.
Refer to issue #6.

[Fix] Add the issue and pull request template.

---

docs/stylesheets/extra.css

improve the UI for mobile device

---

.github/CONTRIBUTING.md

[Docs] Add the CONTRIBUTING guidance.

---

README.md

change the readme.md

---

README.md

Add the special thanks to OI Wiki.

[Docs] Add the special thanks.

---

docs/library/book/2024独家金融干货包/index.md

move all the pdf into https://github.com/LLMQuant/asset/

feat(docs/library): 添加2024独家金融干货包

---

docs/ai/llm/VQVAE.md

feat(docs/ai/llm): add vqvae doc

---

.github/CONTRIBUTING.md
README.md

Polish the contribution related docs, refer to #29

[Docs] Polish the contribution related docs.

---

docs/contribute.md

fix inccorect href link, refer to #29 

[Docs] Fix the incorrect href.

---

docs/javascripts/mathjax.js
mkdocs.yml

small bug and latext rendering issue

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/deploy.yml
.gitignore

[Refactor] Refactor our templates.

---

README.md

Standardize README files for a consistent style.

[Fix] Update README.md

---

docs/contribute.md

[Feat] Better block display.

---

README.md

feat: add star history chart.

---

docs/scholar/index.md

[Fix] fix a display bug

---

.github/workflows/quant_scholar.yml

[Feature] add the quant scholar workflow

---

.github/workflows/quant_scholar.yml

Use deploy key in our workflow yml to bypass branch rule.

[Fix] Try to use deploy key for action workflow.

---

mkdocs.yml

According to `mkdocs` docs: https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/#google-analytics. Our repo can easily integrate google analytics to track some non-sensitive and useful user behaviors.
Attach google analytics official url: https://analytics.google.com/

[Feature] Add google analytics.

---

docs/llmquant_resources/overview.md
mkdocs.yml

[Update] Polish the ads.

---

docs/scholar/index.md

fox quant scholar pic link error

fix quant scholar pic link error
